### ISSUE TITLE
[WIP] WebSocket GUI client v2

### ISSUE THREAD

**Issue by Nishchit14** [firecampapp/Firecamp#116]
## Reference issues
- [ ] Websockets improvements #91 
- [ ] Feature Request : Use same card for recurring events in socket.io testing #63 
- [ ] websocket binary message support #58 
- [ ] Optional Sec-WebSocket-Extensions and extension parameters #55 
- [ ] Send null character to terminate stomp message #45 
- [ ] Ping/Pong #44
